import { access, mkdir, writeFile } from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import { dirname, join } from 'node:path';

type SetupContext = {
  cwd?: string;
  runtime?: {
    log?: (
      level: 'debug' | 'info' | 'warn' | 'error',
      message: string,
      meta?: Record<string, unknown>
    ) => void;
  };
};

const ANALYTICS_DIRS = ['buffer', 'dlq', 'logs'];

export async function run(ctx: SetupContext = {}) {
  const cwd = ctx.cwd ?? process.cwd();
  const analyticsDir = join(cwd, '.kb', 'analytics');
  const created: string[] = [];

  await mkdir(analyticsDir, { recursive: true });

  for (const dir of ANALYTICS_DIRS) {
    const target = join(analyticsDir, dir);
    await mkdir(target, { recursive: true });
    created.push(target);
  }

  await ensureFile(
    join(analyticsDir, '.gitignore'),
    ['# Analytics artifacts', 'buffer/', 'dlq/', 'logs/', '*.json', '*.jsonl', ''].join('\n')
  );

  await ensureFile(
    join(analyticsDir, 'README.md'),
    [
      '# KB Labs Analytics workspace',
      '',
      'This directory stores buffered events, DLQ entries, and diagnostics generated by `kb analytics ...` commands.',
      '',
      'Artifacts are environment-specific and should not be committed.',
      '',
    ].join('\n')
  );

  return {
    ok: true,
    analyticsDir,
    created,
  };
}

async function ensureFile(path: string, contents: string) {
  try {
    await access(path, fsConstants.F_OK);
  } catch {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents, 'utf-8');
  }
}


